# -*- coding: utf-8 -*-
from cycurl.__version__ import (  # noqa: F401
    __curl_version__,
    __description__,
    __title__,
    __version__,
)
from cycurl._curl import *
from cycurl.requests import (
    AsyncSession,
    AsyncWebSocket,
    BrowserType,
    BrowserTypeLiteral,
    CacheBackend,
    Cookies,
    CookieTypes,
    ExtraFingerprints,
    FileCacheBackend,
    Headers,
    HeaderTypes,
    ProxySpec,
    Request,
    Response,
    Session,
    WebSocket,
    WebSocketClosed,
    WebSocketError,
    WebSocketTimeout,
    WsCloseCode,
    delete,
    exceptions,
    get,
    head,
    options,
    patch,
    post,
    put,
    request,
)
from cycurl.fingerprints import Fingerprint, FingerprintManager, get_fingerprint

# __all__ = [
#     "Curl",
#     "AsyncCurl",
#     "CurlMime",
#     "CurlError",
#     "config_warnings",
#     "Session",
#     "AsyncSession",
#     "BrowserType",
#     "BrowserTypeLiteral",
#     "request",
#     "head",
#     "get",
#     "post",
#     "put",
#     "patch",
#     "delete",
#     "options",
#     "Cookies",
#     "Headers",
#     "Request",
#     "Response",
#     "AsyncWebSocket",
#     "WebSocket",
#     "WebSocketError",
#     "WebSocketClosed",
#     "WebSocketTimeout",
#     "WsCloseCode",
#     "ExtraFingerprints",
#     "CookieTypes",
#     "HeaderTypes",
#     "ProxySpec",
#     "exceptions",
# ]
# here, we do not use __all__ because we want constants in _curl.so to be available


config_warnings(on=False)
